#include "programmingmode.h"

void ProgrammingMode::one() {}
void ProgrammingMode::two() {}
void ProgrammingMode::three() {}
void ProgrammingMode::four() {}
void ProgrammingMode::five() {}
void ProgrammingMode::six() {}
void ProgrammingMode::seven() {}
void ProgrammingMode::eigth() {}
void ProgrammingMode::nine() {}
void ProgrammingMode::zero() {}
void ProgrammingMode::change() {}
void ProgrammingMode::push() {}
void ProgrammingMode::plus() {}
void ProgrammingMode::mines() {}
void ProgrammingMode::div() {}
void ProgrammingMode::mul() {}
void ProgrammingMode::VP_1() {}
void ProgrammingMode::VP_2() {}
void ProgrammingMode::CX() {}
void ProgrammingMode::PP() {}
void ProgrammingMode::x_to_mem() {}
void ProgrammingMode::mem_to_x() {}
void ProgrammingMode::dot() {}
void ProgrammingMode::XZ() {}
void ProgrammingMode::r() {}
void ProgrammingMode::l() {}
void ProgrammingMode::BO() {}
void ProgrammingMode::SP() {}
